CREATE DATABASE IF NOT EXISTS link_management;
USE link_management;

CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT,
  fullname VARCHAR(255),
  ip_address VARCHAR(50),
  is_guest BOOLEAN,
  email VARCHAR(100),
  password VARCHAR(100),
  username VARCHAR(100),
  avatar VARCHAR(500),
  provider VARCHAR(50),
  status VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS links(
  id INT AUTO_INCREMENT,
  user_id INT NOT NULL,
  url_title VARCHAR(500),
  url_icon VARCHAR(500),
  code VARCHAR(255),
  main_url VARCHAR(500),
  domain VARCHAR(500),
  status VARCHAR(100),
  deleted BOOLEAN DEFAULT FALSE,
  deletedAt TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS one_time_codes(
  id INT AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL,
  ref_email VARCHAR(100) NOT NULL,
  expired_at TIMESTAMP,
  is_verify BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS logs_action(
  id INT AUTO_INCREMENT,
  link_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (link_id) REFERENCES links(id)
)