CREATE DATABASE IF NOT EXISTS link_management;
USE link_management;

CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT,
  fullname VARCHAR(255),
  ip_address VARCHAR(50),
  is_guest BOOLEAN,
  email VARCHAR(100),
  password VARCHAR(100),
  username VARCHAR(100),
  status VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS links(
  id INT AUTO_INCREMENT,
  user_id INT NOT NULL,
  code VARCHAR(255),
  main_url VARCHAR(500),
  view INT,
  status VARCHAR(100),
  deleted BOOLEAN,
  deletedAt TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS one_time_codes(
  id INT AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL,
  ref_email VARCHAR(100) NOT NULL,
  expired_at TIMESTAMP,
  is_verify BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (id)
);